name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '14'
      - name: Cache ~/.pnpm-store
        uses: actions/cache@main
        with:
          path: ~/.pnpm-store
          key: ${{ runner.os }}-${{ matrix.node-version }}-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-${{ matrix.node-version }}
      - run: npm install -g pnpm
      - name: Install dependencies
        run: pnpm install --frozen-lockfile
      - name: Run Prettier
        run: pnpm format
      - name: Run ESLint
        run: pnpm lint
      - name: Run svelte-check
        run: pnpm check
      - name: Run Cypress
        uses: cypress-io/github-action@v2
        with:
          install: false
          build: pnpm build
          start: pnpm preview
          wait-on: 'http://localhost:3000'
          config-file: cypress.json
