name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install pnpm
        uses: pnpm/action-setup@v2
        with:
          version: latest
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 16.x
          cache: pnpm
      - name: Install dependencies
        run: pnpm install --frozen-lockfile
      - name: Run Build
        run: pnpm build
      - name: Run ESLint
        run: pnpm lint
      - name: Run svelte-check
        run: pnpm check
      - name: Run Cypress
        uses: cypress-io/github-action@v4
        with:
          install: false
          build: pnpm build
          start: pnpm preview
          wait-on: 'http://localhost:4173/'
